---
title: "A3: Incarceration"
output: html_document
---

### Introduction

An introduction of the problem domain and a description of the variable(s) you are choosing to analyze (and why!)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

These will likely be calculated using your DPLYR skills, answering questions such as: 

- What is the average value of my variable across all the counties (in the current year)?
- Where is my variable the highest / lowest?
- How much has my variable change over the last N years?

Feel free to calculate and report values that you find relevant. Again, remember that the purpose is to think about how these measure of incarceration vary by race.

### The Dataset

Who collected the data?  

The data was collected by the Vera Institute of Justice.

How was the data collected or generated?  

The data was collected in various ways by the Vera Institute. Some ways are from the government and government agencies, criminal settings such as jails and courtrooms, city/town halls. This Washington dataset may have been retrieved using data from the WA state government and similar areas.

Why was the data collected? 

The data was collected in order to bring about ending mass incarceration and searching for solutions to do that. The Vera Institute wants to transform the justice system and they can do so by studying prison populations and demographics of who is in prison to determine if there's bias towards particular groups of people.

How many observations (rows) are in your data?  



How many features (columns) are in the data? 



What, if any, ethical questions or questions of power do you need to consider when working with this data?  



What are possible limitations or problems with this data?   (at least 200 words)

This data only has the races of people who are in prison in WA state, and it's a small amount of data compared to the entire set. The data also does not have the reasonings behind why prisoners are in prison.



### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

